"""empty message

Revision ID: 22eedebbf7b2
Revises: 98b323fc2959
Create Date: 2023-09-01 18:55:03.937975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '22eedebbf7b2'
down_revision = '98b323fc2959'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coaster', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=256), nullable=True))

    with op.batch_alter_table('park', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=256), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('profile_pic', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_pic')

    with op.batch_alter_table('park', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    with op.batch_alter_table('coaster', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
